### PR TITLE
More improvements about Plone theme package

### PR DESCRIPTION
**Pull request by macagua**
@d2m can you check these improvements and if all are Ok, can merged it?

### CODE REVIEW

**Review by thet — APPROVED** [review]
LGTM

**Comment by thet** [comment]
Actually, one thing: this theme is not used on zope.org nor zope.de anymore.

I wanted to suggest to fork this repo into zopefoundation, but I think it doesn't make sense given it is not used anymore.

Are you planning to use it somewhere?

**Comment by macagua** [comment]
@thet thanks you for merged it!

Well I think so, maybe move it at plone collective organization, I am planning to use as part of [plonethemes.suite](https://github.com/plone-ve/plonethemes.suite) iniciative

**Comment by macagua** [comment]
@thet I propose this, I can transfer my forked repository into collective organization, in this way it remains a reference that was a fork of your original repository.

Why my forked repository?

1- my forked repository is more tagged with github category and description, yo know in collective organization can chance theses things later you transfer the rigths

2- when you tranfer a forked repository into collective organization, it is giving credit to repository upstream, like this example https://github.com/collective/plonetheme.chalkboard

what do you think about it?

**Pull request merged**
